<?php

return [
    'image_compress' => [
        'slug' => 'image-compress',
        'legacy_slugs' => [],
        'icon' => '🖼️',
        'title_key' => 'image_compress',
        'description_key' => 'image-compress_description',
        'keywords_key' => 'image-compress_keywords',
    ],
    'time_clock' => [
        'slug' => 'time-clock',
        'legacy_slugs' => [],
        'icon' => '⏰',
        'title_key' => 'time_clock',
        'description_key' => 'time-clock_description',
        'keywords_key' => 'time-clock_keywords',
    ],
    'unit_converter' => [
        'slug' => 'unit-converter',
        'legacy_slugs' => ['nav_unit'],
        'icon' => '♻️',
        'title_key' => 'unit_converter',
        'description_key' => 'unit-converter_description',
        'keywords_key' => 'unit-converter_keywords',
    ],
    'scientific_calculator' => [
        'slug' => 'scientific-calculator',
        'legacy_slugs' => ['scientific_calculator'],
        'icon' => '🧮',
        'title_key' => 'scientific_calculator',
        'description_key' => 'scientific-calculator_description',
        'keywords_key' => 'scientific-calculator_keywords',
    ],
    'color_picker' => [
        'slug' => 'color-picker',
        'legacy_slugs' => ['color‐picker'],
        'icon' => '🎨',
        'title_key' => 'color_picker',
        'description_key' => 'color-picker_description',
        'keywords_key' => 'color-picker_keywords',
    ],
    'qr_code_generator' => [
        'slug' => 'qr-code-generator',
        'legacy_slugs' => [],
        'icon' => '🔳',
        'title_key' => 'qr_code_generator',
        'description_key' => 'qr-code-generator_description',
        'keywords_key' => 'qr-code-generator_keywords',
    ],
    'json_formatter' => [
        'slug' => 'json-formatter',
        'legacy_slugs' => [],
        'icon' => '🧾',
        'title_key' => 'json_formatter',
        'description_key' => 'json-formatter_description',
        'keywords_key' => 'json-formatter_keywords',
    ],
    'base64_encode_decode' => [
        'slug' => 'base64-encode-decode',
        'legacy_slugs' => [],
        'icon' => '🔐',
        'title_key' => 'base64_encode_decode',
        'description_key' => 'base64-encode-decode_description',
        'keywords_key' => 'base64-encode-decode_keywords',
    ],
    'url_encode_decode' => [
        'slug' => 'url-encode-decode',
        'legacy_slugs' => [],
        'icon' => '🔗',
        'title_key' => 'url_encode_decode',
        'description_key' => 'url-encode-decode_description',
        'keywords_key' => 'url-encode-decode_keywords',
    ],
    'timestamp_converter' => [
        'slug' => 'timestamp-converter',
        'legacy_slugs' => [],
        'icon' => '🕓',
        'title_key' => 'timestamp_converter',
        'description_key' => 'timestamp-converter_description',
        'keywords_key' => 'timestamp-converter_keywords',
    ],
    'password_generator' => [
        'slug' => 'password-generator',
        'legacy_slugs' => [],
        'icon' => '🔑',
        'title_key' => 'password_generator',
        'description_key' => 'password-generator_description',
        'keywords_key' => 'password-generator_keywords',
    ],
    'word_counter' => [
        'slug' => 'word-counter',
        'legacy_slugs' => [],
        'icon' => '📝',
        'title_key' => 'word_counter',
        'description_key' => 'word-counter_description',
        'keywords_key' => 'word-counter_keywords',
    ],
    'slug_generator' => [
        'slug' => 'slug-generator',
        'legacy_slugs' => [],
        'icon' => '🏷️',
        'title_key' => 'slug_generator',
        'description_key' => 'slug-generator_description',
        'keywords_key' => 'slug-generator_keywords',
    ],
    'uuid_generator' => [
        'slug' => 'uuid-generator',
        'legacy_slugs' => [],
        'icon' => '🆔',
        'title_key' => 'uuid_generator',
        'description_key' => 'uuid-generator_description',
        'keywords_key' => 'uuid-generator_keywords',
    ],
    'date_difference_calculator' => [
        'slug' => 'date-difference-calculator',
        'legacy_slugs' => [],
        'icon' => '📅',
        'title_key' => 'date_difference_calculator',
        'description_key' => 'date-difference-calculator_description',
        'keywords_key' => 'date-difference-calculator_keywords',
    ],
    'hash_generator' => [
        'slug' => 'hash-generator',
        'legacy_slugs' => [],
        'icon' => '🔣',
        'title_key' => 'hash_generator',
        'description_key' => 'hash-generator_description',
        'keywords_key' => 'hash-generator_keywords',
    ],
    'jwt_decoder' => [
        'slug' => 'jwt-decoder',
        'legacy_slugs' => [],
        'icon' => '🎟️',
        'title_key' => 'jwt_decoder',
        'description_key' => 'jwt-decoder_description',
        'keywords_key' => 'jwt-decoder_keywords',
    ],
    'regex_tester' => [
        'slug' => 'regex-tester',
        'legacy_slugs' => [],
        'icon' => '🧪',
        'title_key' => 'regex_tester',
        'description_key' => 'regex-tester_description',
        'keywords_key' => 'regex-tester_keywords',
    ],
    'case_converter' => [
        'slug' => 'case-converter',
        'legacy_slugs' => [],
        'icon' => '🔠',
        'title_key' => 'case_converter',
        'description_key' => 'case-converter_description',
        'keywords_key' => 'case-converter_keywords',
    ],
    'line_deduplicator' => [
        'slug' => 'line-deduplicator',
        'legacy_slugs' => [],
        'icon' => '🧹',
        'title_key' => 'line_deduplicator',
        'description_key' => 'line-deduplicator_description',
        'keywords_key' => 'line-deduplicator_keywords',
    ],
    'line_sorter' => [
        'slug' => 'line-sorter',
        'legacy_slugs' => [],
        'icon' => '↕️',
        'title_key' => 'line_sorter',
        'description_key' => 'line-sorter_description',
        'keywords_key' => 'line-sorter_keywords',
    ],
    'markdown_preview' => [
        'slug' => 'markdown-preview',
        'legacy_slugs' => [],
        'icon' => '📄',
        'title_key' => 'markdown_preview',
        'description_key' => 'markdown-preview_description',
        'keywords_key' => 'markdown-preview_keywords',
    ],
    'qr_code_scanner' => [
        'slug' => 'qr-code-scanner',
        'legacy_slugs' => [],
        'icon' => '📷',
        'title_key' => 'qr_code_scanner',
        'description_key' => 'qr-code-scanner_description',
        'keywords_key' => 'qr-code-scanner_keywords',
    ],
    'age_calculator' => [
        'slug' => 'age-calculator',
        'legacy_slugs' => [],
        'icon' => '🎂',
        'title_key' => 'age_calculator',
        'description_key' => 'age-calculator_description',
        'keywords_key' => 'age-calculator_keywords',
    ],
    'percentage_calculator' => [
        'slug' => 'percentage-calculator',
        'legacy_slugs' => [],
        'icon' => '📊',
        'title_key' => 'percentage_calculator',
        'description_key' => 'percentage-calculator_description',
        'keywords_key' => 'percentage-calculator_keywords',
    ],
    'word_pdf_converter' => [
        'slug' => 'word-pdf-converter',
        'legacy_slugs' => [],
        'icon' => '📘',
        'title_key' => 'word_pdf_converter',
        'description_key' => 'word-pdf-converter_description',
        'keywords_key' => 'word-pdf-converter_keywords',
    ],
];
